name: AI Code Review Workflow

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  ai-code-review:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    
    - name: Install Node.js Dependencies
      run: |
        cd ai-code-reviewer
        npm install
    
    - name: Start Backend Server
      run: |
        cd backend
        nohup python main.py &
        sleep 10  # Wait for server to start
    
    - name: Perform Comprehensive Code Review
      run: |
        mkdir -p ai-review-output
        
        review_file() {
          local file="$1"
          local filename=$(basename "$file")
          
          # Send file to review endpoint
          response=$(curl -s -X POST http://localhost:5000/api/review \
            -H "Content-Type: application/json" \
            -d "{\"code\": \"$(cat "$file" | sed 's/"/\\"/g')\", \"fileName\": \"$filename\"}")
          
          # Save review to markdown
          echo "$response" | jq -r '.reviewResults | to_entries[] | "## \(.key)\n\(.value)"' > "ai-review-output/${filename}_review.md"
        }
        
        # Find and review specific file types
        find . -type f \( \
          -name "*.py" -o \
          -name "*.ts" -o \
          -name "*.tsx" -o \
          -name "*.js" -o \
          -name "*.jsx" \
        \) -not -path "*/node_modules/*" | while read -r file; do
          review_file "$file"
        done
        
        # Generate summary report
        echo "# AI Code Review Summary" > ai-review-output/REVIEW_SUMMARY.md
        echo "## Overview" >> ai-review-output/REVIEW_SUMMARY.md
        echo "- Total files reviewed: $(find . -type f \( -name "*.py" -o -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.jsx" \) -not -path "*/node_modules/*" | wc -l)" >> ai-review-output/REVIEW_SUMMARY.md
        echo "- Review Timestamp: $(date)" >> ai-review-output/REVIEW_SUMMARY.md
    
    - name: Upload Review Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ai-code-review-results
        path: ai-review-output/
    
    - name: Commit Review Results
      env:
        GITHUB_TOKEN: ${{ secrets.GB_TOKEN }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git remote set-url origin https://github.com/Rubbershredder/code-reviewer.git
        git add ai-review-output/
        git commit -m "Add AI Code Review Results" || exit 0
        git push